#!/bin/sh
export PIPEWIRE_RUNTIME_DIR=@PIPEWIRE_RUNTIME_DIR@
export PULSE_SERVER=@PULSE_SERVER@
: "${XDG_RUNTIME_DIR:=@PIPEWIRE_RUNTIME_DIR@}"
export XDG_RUNTIME_DIR
# Electron adds --no-sandbox when this is set; Android has no user namespaces for it to use.
export ELECTRON_DISABLE_SANDBOX=1
# Performance / GPU environment generated by Local Desktop on every start from
# /etc/localdesktop/localdesktop.toml, then the user's own overrides.
[ -r /etc/localdesktop/session-env.sh ] && . /etc/localdesktop/session-env.sh
[ -r /etc/localdesktop/session-env.local ] && . /etc/localdesktop/session-env.local
exec startxfce4 --wayland "$@"
