use crate::android::backend::wayland::{
    input::{
        RelativePosition, WinitInput, WinitKeyboardInputEvent, WinitMouseInputEvent,
        WinitMouseMovedEvent, WinitMouseWheelEvent, WinitTouchCancelledEvent, WinitTouchEndedEvent,
        WinitTouchMovedEvent, WinitTouchStartedEvent,
    },
    keymap::physicalkey_to_scancode,
    WaylandBackend,
};
use smithay::backend::input::InputEvent;
use smithay::utils::{Physical, Size};
use winit::dpi::PhysicalPosition;
use winit::event::{ElementState, MouseScrollDelta, Touch, TouchPhase, WindowEvent};

/// Specific events generated by Winit
#[derive(Debug)]
pub enum CentralizedEvent {
    /// The window has been resized
    Resized {
        /// The new physical size (in pixels)
        size: Size<i32, Physical>,
        /// The new scale factor
        scale_factor: f64,
    },

    /// The focus state of the window changed
    Focus(bool),

    /// An input event occurred.
    Input(InputEvent<WinitInput>),

    /// The user requested to close the window.
    CloseRequested,

    /// A redraw was requested
    Redraw,

    /// TODO: Support these events
    Unsupported,
}

fn centralize_keyboard(
    scancode: u32,
    state: ElementState,
    time: u64,
    backend: &mut WaylandBackend,
) -> CentralizedEvent {
    match state {
        ElementState::Pressed => backend.key_counter += 1,
        ElementState::Released => {
            backend.key_counter = backend.key_counter.saturating_sub(1);
        }
    };

    let event = InputEvent::Keyboard {
        event: WinitKeyboardInputEvent {
            time,
            key: scancode,
            count: backend.key_counter,
            state,
        },
    };
    CentralizedEvent::Input(event)
}

pub fn centralize_injected_keyboard(
    scancode: u32,
    state: ElementState,
    time: u64,
    backend: &mut WaylandBackend,
) -> CentralizedEvent {
    centralize_keyboard(scancode, state, time, backend)
}

pub fn centralize(event: WindowEvent, backend: &mut WaylandBackend) -> CentralizedEvent {
    let time = backend.clock.now().as_millis() as u64;
    return match event {
        WindowEvent::Resized(size) => {
            let (w, h): (i32, i32) = size.into();

            CentralizedEvent::Resized {
                size: (w, h).into(),
                scale_factor: backend.scale_factor,
            }
        }
        WindowEvent::ScaleFactorChanged {
            scale_factor: new_scale_factor,
            ..
        } => {
            backend.scale_factor = new_scale_factor;
            let (w, h): (i32, i32) = backend
                .graphic_renderer
                .as_ref()
                .unwrap()
                .window()
                .inner_size()
                .into();
            CentralizedEvent::Resized {
                size: (w, h).into(),
                scale_factor: backend.scale_factor,
            }
        }
        WindowEvent::RedrawRequested => CentralizedEvent::Redraw,
        WindowEvent::CloseRequested => CentralizedEvent::CloseRequested,
        WindowEvent::Focused(focused) => CentralizedEvent::Focus(focused),
        WindowEvent::KeyboardInput {
            event,
            is_synthetic,
            ..
        } if !is_synthetic && !event.repeat => {
            let scancode = physicalkey_to_scancode(event.physical_key).unwrap_or(0);
            centralize_keyboard(scancode, event.state, time, backend)
        }
        WindowEvent::CursorMoved { position, .. } => {
            let size = backend
                .graphic_renderer
                .as_ref()
                .unwrap()
                .window()
                .inner_size();
            let x = position.x / size.width as f64;
            let y = position.y / size.height as f64;
            let event = InputEvent::PointerMotionAbsolute {
                event: WinitMouseMovedEvent {
                    time,
                    position: RelativePosition::new(x, y),
                    global_position: position,
                },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::MouseWheel { delta, .. } => {
            let event = InputEvent::PointerAxis {
                event: WinitMouseWheelEvent { time, delta },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::MouseInput { state, button, .. } => {
            let event = InputEvent::PointerButton {
                event: WinitMouseInputEvent {
                    time,
                    button,
                    state,
                    is_x11: false,
                },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Started,
            location,
            id,
            ..
        }) => {
            backend.touch_points.insert(id, location);
            if backend.touch_points.len() >= 2 {
                // Second finger down: transition to two-finger scroll mode.
                // Initialize the centroid so the first move has a reference point.
                backend.scroll_centroid = Some(centroid(&backend.touch_points));
                CentralizedEvent::Unsupported
            } else {
                let size = backend
                    .graphic_renderer
                    .as_ref()
                    .unwrap()
                    .window()
                    .inner_size();
                let x = location.x / size.width as f64;
                let y = location.y / size.height as f64;
                CentralizedEvent::Input(InputEvent::TouchDown {
                    event: WinitTouchStartedEvent {
                        time,
                        global_position: location,
                        position: RelativePosition::new(x, y),
                        id,
                    },
                })
            }
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Moved,
            location,
            id,
            ..
        }) => {
            backend.touch_points.insert(id, location);
            if backend.touch_points.len() >= 2 {
                // Two-finger scroll: emit a PointerAxis event based on centroid delta.
                let new_centroid = centroid(&backend.touch_points);
                if let Some(last) = backend.scroll_centroid {
                    let dx = new_centroid.x - last.x;
                    let dy = new_centroid.y - last.y;
                    backend.scroll_centroid = Some(new_centroid);
                    if dx != 0.0 || dy != 0.0 {
                        return CentralizedEvent::Input(InputEvent::PointerAxis {
                            event: WinitMouseWheelEvent {
                                time,
                                delta: MouseScrollDelta::PixelDelta(PhysicalPosition {
                                    x: -dx,
                                    y: -dy,
                                }),
                            },
                        });
                    }
                } else {
                    backend.scroll_centroid = Some(new_centroid);
                }
                CentralizedEvent::Unsupported
            } else {
                let size = backend
                    .graphic_renderer
                    .as_ref()
                    .unwrap()
                    .window()
                    .inner_size();
                let x = location.x / size.width as f64;
                let y = location.y / size.height as f64;
                CentralizedEvent::Input(InputEvent::TouchMotion {
                    event: WinitTouchMovedEvent {
                        time,
                        position: RelativePosition::new(x, y),
                        global_position: location,
                        id,
                    },
                })
            }
        }

        WindowEvent::Touch(Touch {
            phase: TouchPhase::Ended,
            id,
            ..
        }) => {
            let was_scrolling = backend.touch_points.len() >= 2;
            backend.touch_points.remove(&id);
            backend.scroll_centroid = if backend.touch_points.len() >= 2 {
                Some(centroid(&backend.touch_points))
            } else {
                None
            };
            if was_scrolling {
                // Don't forward a stray TouchUp after a two-finger gesture.
                CentralizedEvent::Unsupported
            } else {
                CentralizedEvent::Input(InputEvent::TouchUp {
                    event: WinitTouchEndedEvent { time, id },
                })
            }
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Cancelled,
            id,
            ..
        }) => {
            let was_scrolling = backend.touch_points.len() >= 2;
            backend.touch_points.remove(&id);
            backend.scroll_centroid = None;
            if was_scrolling {
                CentralizedEvent::Unsupported
            } else {
                CentralizedEvent::Input(InputEvent::TouchCancel {
                    event: WinitTouchCancelledEvent { time, id },
                })
            }
        }

        _ => {
            log::info!("Unhandled event: {:?}", event);
            CentralizedEvent::Unsupported
        }
    };
}

fn centroid(
    points: &std::collections::HashMap<u64, PhysicalPosition<f64>>,
) -> PhysicalPosition<f64> {
    let n = points.len() as f64;
    let (sx, sy) = points
        .values()
        .fold((0.0, 0.0), |(sx, sy), p| (sx + p.x, sy + p.y));
    PhysicalPosition {
        x: sx / n,
        y: sy / n,
    }
}
