//! Text the setup writes into the guest: scripts, environment files and config rewrites.
//!
//! Everything here is a pure function of its inputs (no I/O), so it is unit-tested on the host.
//! The scripts live as real files in `src/android/proot/guest/` (so they can be linted with
//! `bash -n`) and are embedded at build time.

use crate::core::config::{
    DisplayConfig, GpuConfig, LocalConfig, MESA_KGSL_PREFIX, PACMAN_MIRRORS,
    PIPEWIRE_GUEST_RUNTIME_DIR, PULSE_GUEST_SERVER,
};

pub const OUTPUT_LIB: &str = include_str!("../android/proot/guest/output-lib.sh");
pub const OUTPUT_WATCHER: &str = include_str!("../android/proot/guest/output-watcher.sh");
pub const UPDATE_SCRIPT: &str = include_str!("../android/proot/guest/update.sh");
pub const GPU_PROBE_SCRIPT: &str = include_str!("../android/proot/guest/gpu-probe.sh");
pub const BOX64_PRESET_SCRIPT: &str = include_str!("../android/proot/guest/box64-preset.sh");
pub const KEYRING_REGEN_SCRIPT: &str = include_str!("../android/proot/guest/keyring-regen.sh");

/// Guest path of the environment file generated on every start.
pub const SESSION_ENV_PATH: &str = "/etc/localdesktop/session-env.sh";
/// Guest path of the user's own session overrides (never written by Local Desktop).
pub const SESSION_ENV_LOCAL_PATH: &str = "/etc/localdesktop/session-env.local";
/// Guest path of the GPU environment, present only while `[gpu] enabled = true`.
pub const GPU_ENV_PATH: &str = "/etc/localdesktop/gpu-env.sh";

/// UI scale derived from the Android density: `density / 160 * 1.1`, rounded to the nearest
/// 0.25, at least 1.0. Same rule the compositor uses for the host side of the output contract.
pub fn auto_ui_scale(density_dpi: i32) -> f32 {
    ((density_dpi as f32 / 160.0 * 1.1) * 4.0).round().max(4.0) / 4.0
}

/// The UI scale in effect: the configured `ui_scale` when positive, the automatic one otherwise.
pub fn effective_ui_scale(display: &DisplayConfig, density_dpi: i32) -> f32 {
    if display.ui_scale > 0.0 {
        display.ui_scale
    } else {
        auto_ui_scale(density_dpi)
    }
}

/// Plain integer DPI for xfconf's `/Xft/DPI` (96 at scale 1). xfsettingsd multiplies by 1024
/// itself when it publishes the XSETTINGS value to X clients.
pub fn xft_dpi(scale: f32) -> i32 {
    (scale * 96.0).round() as i32
}

pub fn render_session_init(xft_dpi: i32) -> String {
    include_str!("../android/proot/guest/session-init.sh")
        .replace("@XFT_DPI@", &xft_dpi.to_string())
}

pub fn render_startxfce4() -> String {
    include_str!("../android/proot/guest/startxfce4.sh")
        .replace("@PIPEWIRE_RUNTIME_DIR@", PIPEWIRE_GUEST_RUNTIME_DIR)
        .replace("@PULSE_SERVER@", PULSE_GUEST_SERVER)
}

pub fn render_gpu_probe() -> String {
    GPU_PROBE_SCRIPT.replace("@MESA_PREFIX@", MESA_KGSL_PREFIX)
}

/// `/etc/localdesktop/session-env.sh`: performance and GPU environment sourced by
/// `startxfce4-localdesktop` before the desktop starts. Regenerated on every app start, so the
/// result always follows `localdesktop.toml`.
pub fn session_env(config: &LocalConfig, cpus: usize) -> String {
    let mut env = String::from(
        "# Generated by Local Desktop on every start from /etc/localdesktop/localdesktop.toml.\n\
# Do not edit: put your own overrides in /etc/localdesktop/session-env.local instead.\n",
    );
    env.push_str(&format!(
        "\n# llvmpipe (software OpenGL) worker threads: one per CPU.\nexport LP_NUM_THREADS={}\n",
        cpus.max(1)
    ));

    const SOFTWARE_RENDERING: &str = "\
# GTK 4 draws through the OpenGL renderer by default, which is slow on llvmpipe.
export GSK_RENDERER=cairo
# Skip driver probing: llvmpipe is the only OpenGL implementation without the GPU option.
export LIBGL_ALWAYS_SOFTWARE=1
# labwc has no GPU buffers to render with, so wlroots uses its CPU (pixman) renderer.
export WLR_RENDERER=pixman
";

    if config.gpu.enabled {
        env.push_str(&format!(
            "\n# [gpu] enabled = true: Mesa KGSL build in {prefix}, once its installation has finished.\n\
if [ -r {gpu_env} ] && [ -e {prefix}/.release ]; then\n    . {gpu_env}\nelse\n",
            prefix = MESA_KGSL_PREFIX,
            gpu_env = GPU_ENV_PATH,
        ));
        for line in SOFTWARE_RENDERING.lines() {
            env.push_str("    ");
            env.push_str(line);
            env.push('\n');
        }
        env.push_str("fi\n");
    } else {
        env.push('\n');
        env.push_str(SOFTWARE_RENDERING);
    }

    if config.x86.wine {
        env.push_str(
            "\n# Wine under Box64 in proot: no futex/eventfd semantics for esync/fsync.\n\
export WINEESYNC=0\nexport WINEFSYNC=0\n",
        );
    }
    env
}

/// `/etc/localdesktop/gpu-env.sh`: the KGSL Mesa environment for `[gpu] enabled = true`.
pub fn gpu_env(gpu: &GpuConfig) -> String {
    let zink = gpu.driver.trim().eq_ignore_ascii_case("zink");
    let mut env = format!(
        "# Generated by Local Desktop: environment for the experimental Adreno GPU path.\n\
# Mesa {release} (lfdevs/mesa-for-android-container) with the KGSL backend lives in a separate\n\
# prefix; this file is only sourced while [gpu] enabled = true, so the stock Mesa returns when it is off.\n\
prefix={prefix}\n\
export LD_LIBRARY_PATH=\"$prefix/usr/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}\"\n\
export LIBGL_DRIVERS_PATH=\"$prefix/usr/lib/dri\"\n\
export GBM_BACKENDS_PATH=\"$prefix/usr/lib/gbm\"\n\
export __EGL_VENDOR_LIBRARY_FILENAMES=\"$prefix/usr/share/glvnd/egl_vendor.d/50_mesa.json\"\n\
export DRIRC_CONFIGDIR=\"$prefix/usr/share/drirc.d\"\n\
export VK_ICD_FILENAMES=\"$prefix/usr/share/vulkan/icd.d/freedreno_icd.aarch64.json\"\n\
export VK_DRIVER_FILES=\"$VK_ICD_FILENAMES\"\n",
        release = crate::core::config::MESA_KGSL_RELEASE,
        prefix = MESA_KGSL_PREFIX,
    );

    if zink {
        env.push_str(
            "\n# [gpu] driver = \"zink\": OpenGL through Zink on the Turnip Vulkan driver.\n\
export MESA_LOADER_DRIVER_OVERRIDE=zink\n\
export GALLIUM_DRIVER=zink\n\
export ZINK_CONTEXT_THREADED=1\n",
        );
    } else {
        env.push_str(
            "\n# [gpu] driver = \"freedreno\": OpenGL/GLES directly on Freedreno over KGSL.\n\
export MESA_LOADER_DRIVER_OVERRIDE=kgsl\n",
        );
    }

    env.push_str(
        "\n# Turnip on Adreno 8xx needs LRZ off (GameNative uses the same workaround). The model is\n\
# read from KGSL; when it cannot be read the flag is set, as this build targets Adreno 8xx.\n\
gpu_model=\"\"\n\
{ read -r gpu_model; } 2>/dev/null < /sys/class/kgsl/kgsl-3d0/gpu_model\n\
case \"$gpu_model\" in\n\
    Adreno[0-7]*) ;;\n\
    *) export TU_DEBUG=\"${TU_DEBUG:+$TU_DEBUG,}nolrz\" ;;\n\
esac\n\
unset gpu_model\n\
\n\
# Present path. With a zwp_linux_dmabuf_v1 global on the host compositor, buffers are shared\n\
# zero-copy and labwc may render with GLES. Without it clients render on the GPU but hand frames\n\
# over through wl_shm (one copy), and labwc stays on the CPU renderer.\n\
if command -v wayland-info >/dev/null 2>&1 &&\n\
    WAYLAND_DISPLAY=\"${WAYLAND_DISPLAY:-wayland-0}\" XDG_RUNTIME_DIR=\"${XDG_RUNTIME_DIR:-/tmp}\" \\\n\
        timeout 5 wayland-info 2>/dev/null | grep -q zwp_linux_dmabuf_v1; then\n\
    export WLR_RENDERER=gles2\n\
else\n\
    export WLR_RENDERER=pixman\n\
    export LIBGL_KOPPER_DISABLE=true\n\
    export MESA_VK_WSI_DEBUG=sw\n\
fi\n",
    );
    env
}

/// Managed `/etc/pacman.d/mirrorlist`: HTTPS mirrors only.
pub fn managed_mirrorlist() -> String {
    let mut list = String::from(
        "# Arch Linux ARM mirrors over HTTPS. Written once by Local Desktop because the original\n\
# list used plain HTTP; it is only rewritten again if plain-HTTP servers show up in it.\n\
# (The geo-redirector mirror.archlinuxarm.org has no valid TLS certificate, so it is not used.)\n\n",
    );
    for mirror in PACMAN_MIRRORS {
        list.push_str("Server = ");
        list.push_str(mirror);
        list.push('\n');
    }
    list
}

/// `true` when an active (uncommented) `Server` line of the mirror list uses plain HTTP.
pub fn mirrorlist_has_plain_http(content: &str) -> bool {
    content.lines().any(|line| {
        let line = line.trim();
        !line.starts_with('#')
            && line
                .split_once('=')
                .map_or(false, |(key, value)| {
                    key.trim() == "Server" && value.trim().starts_with("http://")
                })
    })
}

const MAKEFLAGS_LINE: &str = "MAKEFLAGS=\"-j$(nproc)\" # Local Desktop: build with every CPU";

/// Enables parallel builds in `makepkg.conf`. A commented-out `MAKEFLAGS` is replaced, a missing
/// one is appended, an active one (set by the user or by us before) is left alone.
/// `None` when nothing has to change.
pub fn ensure_makeflags(content: &str) -> Option<String> {
    let is_assignment = |line: &str, commented: bool| {
        let line = line.trim_start();
        let line = if commented {
            match line.strip_prefix('#') {
                Some(rest) => rest.trim_start(),
                None => return false,
            }
        } else {
            line
        };
        line.starts_with("MAKEFLAGS=")
    };

    if content.lines().any(|line| is_assignment(line, false)) {
        return None;
    }

    let mut replaced = false;
    let mut out = String::with_capacity(content.len() + MAKEFLAGS_LINE.len() + 1);
    for line in content.lines() {
        if !replaced && is_assignment(line, true) {
            out.push_str(MAKEFLAGS_LINE);
            replaced = true;
        } else {
            out.push_str(line);
        }
        out.push('\n');
    }
    if !replaced {
        out.push_str(MAKEFLAGS_LINE);
        out.push('\n');
    }
    Some(out)
}

/// Firefox autoconfig (`localdesktop.cfg`). The first line has to be a comment.
/// The sandbox preferences are required by proot; the rendering preferences target CPU-only
/// rendering and are skipped when the GPU option is on.
pub fn firefox_autoconfig(gpu_enabled: bool) -> String {
    let mut cfg = String::from(
        r#"// Auto updated by Local Desktop on each startup, do not edit manually
defaultPref("media.cubeb.sandbox", false);
defaultPref("security.sandbox.content.level", 0);
defaultPref("media.allow-audio-non-utility", true);
defaultPref("media.rdd-process.enabled", false);
// Fewer content processes and rarer session-store writes: proot counts every process.
defaultPref("dom.ipc.processCount", 4);
defaultPref("browser.sessionstore.interval", 60000);
"#,
    );
    if !gpu_enabled {
        cfg.push_str(
            r#"// CPU-only rendering: WebRender's software backend instead of OpenGL on llvmpipe.
defaultPref("gfx.webrender.software", true);
defaultPref("media.hardware-video-decoding.enabled", false);
"#,
        );
    }
    cfg.push_str(
        r#"
try {
  var { SandboxUtils } = ChromeUtils.importESModule("resource://gre/modules/SandboxUtils.sys.mjs");
  SandboxUtils.maybeWarnAboutDisabledContentSandbox = () => {};
  SandboxUtils.observeContentSandboxPref = () => {};
} catch (_) {}
"#,
    );
    cfg // It is required that the first line of this file is a comment. Docs: https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig
}

/// A freedesktop `.desktop` launcher.
pub fn desktop_entry(
    name: &str,
    comment: &str,
    exec: &str,
    icon: &str,
    terminal: bool,
    extra: &str,
) -> String {
    format!(
        "[Desktop Entry]\nVersion=1.0\nType=Application\nName={name}\nComment={comment}\nExec={exec}\nIcon={icon}\nTerminal={terminal}\nStartupNotify=true\n{extra}"
    )
}

pub fn settings_desktop_entry() -> String {
    desktop_entry(
        "Local Desktop Settings",
        "Edit /etc/localdesktop/localdesktop.toml (display, input, GPU, x86, session). Changes apply on the next app start.",
        "mousepad /etc/localdesktop/localdesktop.toml",
        "preferences-system",
        false,
        "Categories=Settings;System;\n",
    )
}

pub fn update_desktop_entry() -> String {
    desktop_entry(
        "Local Desktop - Update System",
        "Install pending package updates (pacman -Syu), including security fixes",
        "env LOCALDESKTOP_PAUSE=1 /usr/local/bin/localdesktop-update",
        "system-software-update",
        true,
        "Categories=System;\n",
    )
}

pub fn gpu_probe_desktop_entry() -> String {
    desktop_entry(
        "Local Desktop - GPU Probe",
        "Check the experimental GPU path and save a report to /var/log/localdesktop/gpu-probe.txt",
        "env LOCALDESKTOP_PAUSE=1 /usr/local/bin/localdesktop-gpu-probe",
        "utilities-system-monitor",
        true,
        "Categories=System;\n",
    )
}

pub fn wine_config_desktop_entry() -> String {
    desktop_entry(
        "Wine Configuration",
        "Configure Wine (Windows compatibility layer, runs under Box64)",
        "/usr/local/bin/winecfg",
        "wine",
        false,
        "Categories=Settings;Wine;\n",
    )
}

pub fn wine_loader_desktop_entry() -> String {
    desktop_entry(
        "Wine Windows Program Loader",
        "Run a Windows program with Wine (under Box64)",
        "/usr/local/bin/wine start /unix %f",
        "wine",
        false,
        "MimeType=application/x-ms-dos-executable;application/x-msdownload;application/x-msi;application/x-ms-shortcut;\nCategories=Wine;\nNoDisplay=true\n",
    )
}

/// `/usr/local/bin/box64`: Box64 with the default preset (`BOX64_PRESET` selects another).
pub const BOX64_WRAPPER: &str = "#!/bin/sh\n\
# Box64 with the Local Desktop default preset. Choose another one with BOX64_PRESET=performance\n\
# (stability, compatibility, intermediate, performance, denuvo, unity) or call box64-preset directly.\n\
exec /usr/local/bin/box64-preset \"${BOX64_PRESET:-compatibility}\" \"$@\"\n";

pub const X64_WRAPPER: &str = "#!/bin/sh\nexec /usr/local/bin/box64 \"$@\"\n";

/// `/usr/local/bin/wine`: the x86_64 Wine build in `/opt/wine`, run through Box64.
pub const WINE_WRAPPER: &str = "#!/bin/sh\n\
# Wine (x86_64, WoW64) under Box64. Prefix: ~/.wine unless WINEPREFIX is set.\n\
: \"${WINEPREFIX:=$HOME/.wine}\"\n\
export WINEPREFIX\n\
# proot has no futex/eventfd semantics for esync/fsync.\n\
export WINEESYNC=0 WINEFSYNC=0\n\
export WINEDEBUG=\"${WINEDEBUG:--all}\"\n\
# winemenubuilder is slow under proot and litters the menu; re-enable with WINEDLLOVERRIDES=\"\".\n\
export WINEDLLOVERRIDES=\"${WINEDLLOVERRIDES-winemenubuilder.exe=d}\"\n\
exec /usr/local/bin/box64 /opt/wine/bin/wine \"$@\"\n";

pub const WINESERVER_WRAPPER: &str = "#!/bin/sh\n\
: \"${WINEPREFIX:=$HOME/.wine}\"\n\
export WINEPREFIX\n\
exec /usr/local/bin/box64 /opt/wine/bin/wineserver \"$@\"\n";

/// Wine tools that are `wine` itself in the upstream build; each gets a wrapper naming the program.
pub const WINE_TOOLS: &[&str] = &["winecfg", "wineboot", "regedit", "msiexec", "notepad", "winepath", "winefile", "wineconsole"];

pub fn wine_tool_wrapper(tool: &str) -> String {
    format!("#!/bin/sh\nexec /usr/local/bin/wine {tool} \"$@\"\n")
}

/// `/etc/box64.box64rc`: per-program overrides. Settings priority is `~/.box64rc`, then this
/// file, then environment variables, so it deliberately has no `[*]` section (that would beat
/// the presets); the preset lives in the `box64` wrapper instead.
pub const BOX64_RC: &str = "# Box64 per-program settings, see /usr/share/doc/box64/USAGE.md\n\
#\n\
# Build note: the box64 package comes from the archlinuxcn repository. If a program dies with\n\
# bad signal handling (SIGSEGV storms inside Wine), rebuild Box64 from source with\n\
# `-DARM64=1 -DARM_DYNAREC=ON -DBAD_SIGNAL=ON` (needed on kernels that mix Android and Linux\n\
# signal frames) and install it over /usr/bin/box64.\n\
#\n\
# The entries below are adapted from GameNative (GPL-3.0, https://github.com/utkarshdalal/GameNative,\n\
# app/src/main/assets/box86_64/default.box64rc).\n\
\n\
[steam.exe]\n\
BOX64_ENV=WINEARGS=-no-dwrite -no-cef-sandbox -nooverlay -nobigpicture -nofriendsui -noshaders -novid -noverifyfiles -nointro -skipstreamingdrivers -norepairfiles -nohltv -nofasthtml -nocrashmonitor -no-shared-textures -disablehighdpi -cef-single-process -cef-in-process-gpu -single_core -cef-disable-d3d11 -cef-disable-sandbox -disable-winh264 -vrdisable -cef-disable-breakpad -cef-disable-gpu -cef-disable-hang-timeouts -cef-disable-seccomp-sandbox -cef-disable-extensions -cef-disable-remote-fonts -cef-enable-media-stream -cef-disable-accelerated-video-decode\n\
BOX64_ENV1=WINEDLLOVERRIDES=gameoverlayui,gameoverlayui64.exe=d\n\
\n\
[steamwebhelper.exe]\n\
BOX64_DYNAREC_STRONGMEM=1\n\
\n\
[MgsGroundZeroes.exe]\n\
BOX64_ENV=WINEFORCENTCONTINUE=1\n\
\n\
[farcry3.exe]\n\
BOX64_ENV=WINE_DO_NOT_OPEN_SC_MANAGER=1\n\
\n\
[farcry3_d3d11.exe]\n\
BOX64_ENV=WINE_DO_NOT_OPEN_SC_MANAGER=1\n\
\n\
[FarCry4.exe]\n\
BOX64_ENV=WINVERSION=winxp\n\
\n\
[watch_dogs.exe]\n\
BOX64_ENV=WINVERSION=winxp\n\
\n\
[ffxiiiimg.exe]\n\
BOX64_ENV=WINEARGS=-FullScreenMode=Force -Shadow=512 -Msaa=2\n\
\n\
[kof13_win32_Release.exe]\n\
BOX64_ENV1=WINEDLLOVERRIDES=quartz=d\n\
\n\
[DXMD.exe]\n\
BOX64_ENV=WINEVMEMMAXSIZE=16384\n\
\n\
[rage.exe]\n\
BOX64_ENV=ZINK_CONTEXT_THREADED=0\n\
\n\
[rage64.exe]\n\
BOX64_ENV=ZINK_CONTEXT_THREADED=0\n";

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::config::{LocalConfig, X86Config};

    #[test]
    fn auto_ui_scale_rounds_to_quarters_with_a_floor_of_one() {
        assert_eq!(auto_ui_scale(160), 1.0); // 1.1 rounds down to 1.0
        assert_eq!(auto_ui_scale(120), 1.0);
        assert_eq!(auto_ui_scale(80), 1.0);
        assert_eq!(auto_ui_scale(240), 1.75); // 1.65 rounds to 1.75
        assert_eq!(auto_ui_scale(420), 3.0); // 2.8875 rounds to 3.0
        assert_eq!(auto_ui_scale(480), 3.25); // 3.3 rounds to 3.25
    }

    #[test]
    fn configured_ui_scale_wins() {
        let mut display = DisplayConfig::default();
        assert_eq!(effective_ui_scale(&display, 420), 3.0);
        display.ui_scale = 1.75;
        assert_eq!(effective_ui_scale(&display, 420), 1.75);
    }

    #[test]
    fn xft_dpi_is_plain_dpi() {
        assert_eq!(xft_dpi(1.0), 96);
        assert_eq!(xft_dpi(2.5), 240);
        assert_eq!(xft_dpi(1.75), 168);
    }

    #[test]
    fn scripts_are_unix_scripts() {
        for (name, script) in [
            ("output-watcher", OUTPUT_WATCHER),
            ("update", UPDATE_SCRIPT),
            ("gpu-probe", GPU_PROBE_SCRIPT),
            ("box64-preset", BOX64_PRESET_SCRIPT),
            ("keyring-regen", KEYRING_REGEN_SCRIPT),
        ] {
            assert!(script.starts_with("#!/"), "{name} needs a shebang");
            assert!(!script.contains('\r'), "{name} must use LF line endings");
        }
        assert!(!OUTPUT_LIB.contains('\r'));
        assert!(!render_session_init(96).contains('@'), "unresolved placeholder");
        assert!(!render_startxfce4().contains("@PIPEWIRE"), "unresolved placeholder");
        assert!(!render_gpu_probe().contains("@MESA_PREFIX@"));
    }

    #[test]
    fn watcher_does_not_poll_with_external_processes() {
        // The 1 s loop spawned wlr-randr, awk and sleep per tick; the event-driven one must not sleep.
        assert!(!OUTPUT_WATCHER.contains("sleep"));
        assert!(OUTPUT_WATCHER.contains("read -r -t"));
        assert!(OUTPUT_WATCHER.contains("localdesktop-output.fifo") || OUTPUT_LIB.contains("localdesktop-output.fifo"));
    }

    #[test]
    fn session_env_for_software_rendering() {
        let env = session_env(&LocalConfig::default(), 8);
        assert!(env.contains("export LP_NUM_THREADS=8\n"));
        assert!(env.contains("export GSK_RENDERER=cairo\n"));
        assert!(env.contains("export WLR_RENDERER=pixman\n"));
        assert!(!env.contains("MESA_GL_VERSION_OVERRIDE"));
        assert!(!env.contains("gpu-env.sh"));
        assert!(!env.contains("WINEESYNC"));
    }

    #[test]
    fn session_env_for_the_gpu_option() {
        let mut config = LocalConfig::default();
        config.gpu.enabled = true;
        config.x86 = X86Config { box64: true, wine: true };
        let env = session_env(&config, 0);
        assert!(env.contains("export LP_NUM_THREADS=1\n"), "never zero threads");
        assert!(env.contains(". /etc/localdesktop/gpu-env.sh"));
        assert!(env.contains("export WINEESYNC=0"));
        // The software defaults stay as the fallback until the Mesa build is installed.
        assert!(env.contains("    export WLR_RENDERER=pixman"));
    }

    #[test]
    fn gpu_env_selects_the_driver() {
        let freedreno = gpu_env(&GpuConfig::default());
        assert!(freedreno.contains("export MESA_LOADER_DRIVER_OVERRIDE=kgsl"));
        assert!(!freedreno.contains("GALLIUM_DRIVER"));
        assert!(freedreno.contains("TU_DEBUG"));
        assert!(freedreno.contains("export LIBGL_DRIVERS_PATH=\"$prefix/usr/lib/dri\""));
        assert!(freedreno.contains("prefix=/opt/localdesktop-mesa"));

        let zink = gpu_env(&GpuConfig { enabled: true, driver: "Zink".into() });
        assert!(zink.contains("export GALLIUM_DRIVER=zink"));
        assert!(zink.contains("export VK_ICD_FILENAMES="));
        assert!(!zink.contains("=kgsl"));
    }

    #[test]
    fn mirrorlist_is_rewritten_only_for_plain_http() {
        let original = "## Geo-IP\nServer = http://mirror.archlinuxarm.org/$arch/$repo\n# Server = http://x/$arch/$repo\n";
        assert!(mirrorlist_has_plain_http(original));
        assert!(!mirrorlist_has_plain_http("# Server = http://commented/$arch/$repo\n"));
        let managed = managed_mirrorlist();
        assert!(!mirrorlist_has_plain_http(&managed));
        assert!(managed.lines().filter(|l| l.starts_with("Server = https://")).count() >= 2);
        assert!(!mirrorlist_has_plain_http("Server = https://example.org/$arch/$repo\n"));
    }

    #[test]
    fn makeflags_are_enabled_once() {
        let stock = "CFLAGS=\"-O2\"\n#MAKEFLAGS=\"-j2\"\nOPTIONS=(strip)\n";
        let updated = ensure_makeflags(stock).unwrap();
        assert!(updated.contains("\nMAKEFLAGS=\"-j$(nproc)\""));
        assert!(!updated.contains("#MAKEFLAGS"));
        assert_eq!(ensure_makeflags(&updated), None, "idempotent");
        assert_eq!(ensure_makeflags("MAKEFLAGS=\"-j3\"\n"), None, "user setting is kept");
        assert!(ensure_makeflags("CFLAGS=\"-O2\"\n").unwrap().ends_with("build with every CPU\n"));
    }

    #[test]
    fn firefox_config_keeps_the_sandbox_prefs_and_starts_with_a_comment() {
        for gpu in [false, true] {
            let cfg = firefox_autoconfig(gpu);
            assert!(cfg.starts_with("//"));
            assert!(cfg.contains("security.sandbox.content.level\", 0"));
            assert!(cfg.contains("media.rdd-process.enabled\", false"));
            assert_eq!(cfg.contains("gfx.webrender.software"), !gpu);
        }
    }

    #[test]
    fn launchers_are_valid_desktop_entries() {
        for entry in [
            settings_desktop_entry(),
            update_desktop_entry(),
            gpu_probe_desktop_entry(),
            wine_config_desktop_entry(),
            wine_loader_desktop_entry(),
        ] {
            assert!(entry.starts_with("[Desktop Entry]\n"));
            for key in ["Name=", "Exec=", "Type=Application"] {
                assert!(entry.contains(key), "{entry}");
            }
        }
        assert!(settings_desktop_entry().contains("mousepad /etc/localdesktop/localdesktop.toml"));
    }

    #[test]
    fn box64_rc_has_no_global_section() {
        assert!(!BOX64_RC.contains("[*]"));
        assert!(BOX64_RC.contains("[steamwebhelper.exe]"));
    }
}
